### ISSUE TITLE
在uniapp中使用此框架绘图

### ISSUE THREAD

**Issue by yelloxing** [hai2007/clunch#2]
此框架是否可以提供对uniapp的兼容？

**Comment by hai2007** [comment]
理论上来说是可以做到的，我们在后续会考虑进行更广泛的支持的，具体取决于实际情况，作为个人开源项目，我们的时间有限，敬请理解。

**Comment by hai2007** [comment]
我们将会在下一版本0.3.0开始提供对uni-app的支持，目前处于内测阶段，请知悉。

**Comment by hai2007** [comment]
https://hai2007.gitee.io/clunch/#/polyfill?fixed=uni-app

uni-app在0.3.0开始提供了支持，后续再慢慢改进

**Comment by hai2007** [comment]
1.0.0开始，删除对uni-app的兼容支持。

为什么会删除？主要是考虑到代码管理问题，后期如果想支持，决定采用第三方插件的形式提供。

**Comment by hai2007** [comment]
从1.6.0起，已经正式开始了对uniapp的支持，后续我们会添加更多平台的支持：

https://hai2007.gitee.io/clunch/#/api/enhance-platform?fixed=uni-app
