### ISSUE TITLE
关于c-for导致的scope混乱问题

### ISSUE THREAD

**Issue by hai2007** [hai2007/clunch#6]
代码位于：https://github.com/hai2007/clunch/blob/master/src/core/clunch/instance/update.js 文件的$$updateWithData 方法中，具体行是：186

```js
 let temp = doit([JSON.parse(JSON.stringify(renderAOP[i]))], {}, isSubAttrs, id + "for" + forKey + "-", true);
```

为什么会这样，是因为```c-for```导致了scope的修改

最近有点忙，后续进行修改写法，先登记在这里，如果你知道如何改，也可以帮助我们改进（有任何问题请在下面留言）。

**Comment by yelloxing** [comment]
感觉问题的是如何在回退以后，恢复scope，因为对于回退回来的，孩子导致的scope改变对象这个孩子的兄弟而言，是错误的，或者说应该覆盖的。

**Comment by hai2007** [comment]
面前采用直接覆盖的方式解决

**Comment by tear520** [comment]
哦~
